---
title: "correlation data"
author: "Martin Monkman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(MASS)
library(mvtnorm)

```

## Data creation

This file creates a single table (tibble) and plots with x-y pairs of varying correlation strengths.

The distributions of both X and Y variables are the same:

* mean = 100


## FINAL

```{r}

set.seed(1)

data2 <- MASS::mvrnorm(n = 100,        # Create random data
                 mu = c(100, 100, 100, 100),  # mean values
#                 Sigma = matrix(c(1, 0.8, 0.4, 0.0,
#                                  0.8, 1, 0.6, 0.4,
#                                  0.4, 0.6, 1, 0.4,
#                                  0.0, 0.4, 0.6, 1),
#                                nrow = 4))
                 Sigma = matrix(c(1, 0.9, 0.5, 0.0,
                                  0.9, 1, 0.6, 0.4,
                                  0.5, 0.6, 1, 0.4,
                                  0.0, 0.4, 0.6, 1),
                                nrow = 4))

head(data2)                       # Head of random data

data2 <- as_tibble(data2) 
data2

cor(data2)



```


```{r}
data2a <- data2 |> 
  rename("X" = V1, "R=0.9" = V2, "R=0.5" = V3, "R=0.0" = V4) |> 
  pivot_longer(-X, names_to = "Y_vector", values_to = "Y_value") |> 
  mutate(Y_vector = as_factor(Y_vector))

data2a |> 
ggplot(aes(X, Y_value)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Y_vector)

```


, levels = c("X", "R=0.8", "R=0.4", "R=0.0")

```{r}
data2b <- data2 |> 
  mutate(
    V2 = V2 * -1,
    V3 = V3 * -1,
    V4 = V4 * -1
  ) |> 
  rename("X" = V1, "R=-0.9" = V2, "R=-0.5" = V3, "R=0.0" = V4) |> 
  
  pivot_longer(-X, names_to = "Y_vector", values_to = "Y_value") |> 
  mutate(Y_vector = as_factor(Y_vector))


ggplot(data2b, aes(X, Y_value)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Y_vector)

```


As single facet


```{r}
data2c <- data2 |> 
  mutate(
    "R = -0.9" = 100 - (V2  - 100),
    "R = -0.5" = 100 - (V3  - 100)
  ) |> 
#  rename("X" = V1, "R=-0.8" = V2, "R=-0.4" = V3, "R=0.0" = V4) |> 
  rename("X" = V1, "R = 0.9" = V2, "R = 0.5" = V3, "R = 0.0" = V4) |> 
  pivot_longer(-X, names_to = "Y_vector", values_to = "Y_value") |> 
  mutate(Y_vector = as_factor(Y_vector))

data2c |> 
ggplot(aes(X, Y_value)) +
  geom_point() +
#  geom_smooth(method = "lm") +
  facet_wrap(~Y_vector) +
  labs(
    y = "Y"
  )

#ggsave("correlation_facets.jpg")
```


```{r}
data2d <- data2 |> 
  mutate(
    "R^2 = 0.81 (negative)" = 100 - (V2  - 100),
    "R^2 = 0.25 (negative)" = 100 - (V3  - 100)
  ) |> 
#  rename("X" = V1, "R=-0.8" = V2, "R=-0.4" = V3, "R=0.0" = V4) |> 
  rename("X" = V1, "R^2 = 0.81" = V2, "R^2 = 0.25" = V3, "R^2 = 0.0" = V4) |> 
  pivot_longer(-X, names_to = "Y_vector", values_to = "Y_value") |> 
  mutate(Y_vector = as_factor(Y_vector))


data2d |> 
ggplot(aes(X, Y_value)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Y_vector) +
  labs(
    y = "Y"
  )

#ggsave("regression_facets.jpg")

```

